### ISSUE TITLE
ImportError: DLL load failed while importing onnx_cpp2py_export: 动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by LHSSHL001** [onnx/onnx#6284] opened 2024-08-07 08:05 UTC
# Bug Report

### Is the issue related to model conversion?
1.16.2

![image](https://github.com/user-attachments/assets/46492658-e98a-40c1-9a62-7f0e11c88c7c)
<img width="952" alt="onnx_bug" src="https://github.com/user-attachments/assets/4f0d6581-a62e-4fbb-931b-65eb844a7aae">

**Comment by Chizkiyahu** [comment] 2024-08-07 12:42
is look like #6267

**Comment by justinchuby** [comment] 2024-08-07 14:09
Duplicate of https://github.com/onnx/onnx/issues/6267. We will track it there. Thanks!

**Closed by justinchuby** 2024-08-07 14:09 UTC
Labels: bug
