### ISSUE TITLE
Onnx model running error on tensorflow

### ISSUE THREAD

**Issue by wxcstc** [onnx/onnx#1697] opened 2018-12-18 13:48 UTC
I download inceptipn v1 onnx model from https://github.com/onnx/models/tree/master/inception_v1.
And I refer to the steps from https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowExport.ipynb.
My code is below:
`import numpy as np`
`import onnx`
`from onnx_tf.backend import prepare`
`a = np.load("test_data_0.npz")`
`c = a['inputs'].reshape(1,3,224,224)`
`model = onnx.load('model.onnx')`
`tf_rep = prepare(model)`
`output = tf_rep.run(c)`
`print(np.argmax(output))`
Just return reshape error.
![image](https://user-images.githubusercontent.com/16100055/50158241-92460a80-030e-11e9-9fa2-85ffd62675ae.png)
Anyone know about this?

**Comment by wxcstc** [comment] 2018-12-18 14:10
Well，I just uninstall my old tensorflow(1.4.0)，and install the newest version(1.12.0)，the question was gone...

**Comment by houseroad** [comment] 2018-12-18 19:47
The problem is solved, so close the issue.

**Closed by houseroad** 2018-12-18 19:47 UTC
