### ISSUE TITLE
The checker fails for missing shape, but IR allows it

### ISSUE THREAD

**Issue by matteosal** [onnx/onnx#2932] opened 2020-07-29 16:47 UTC
[IR.md](https://github.com/onnx/onnx/blob/master/docs/IR.md) states that the "shape" property can be missing from input and output specs:

> When the shape property is absent for an input, a tensor value of any shape may be passed from the caller. When the shape property is absent for an output, the caller should expect that the output value may be of any shape.

But running the checker on the attached file fails saying that "shape" is required:
```
>>> model = onnx.load("file.onnx")
>>> onnx.checker.check_model(model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/onnx-1.7.0-py3.6-linux-x86_64.egg/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Field 'shape' of type is required but missing.
```

Am I missing something here? Is the model invalid for some other reason?

[file.zip](https://github.com/onnx/onnx/files/4996240/file.zip)

**Comment by jcwchen** [comment] 2020-07-29 18:03
Hi @matteosal,

Similar to https://github.com/onnx/onnx/issues/2492?
I agree this behavior of checker does not meet the description in IR...
@linkerzhang what do you think about this difference between the new IR and the current checker?

**Comment by skottmckay** [comment] 2020-07-30 05:26
I believe graph inputs require a shape, node inputs do not. 

The shape may have symbolic (dim_param is set) or unknown (neither dim_param or dim_value is set) dimensions in it.

**Comment by linkerzhang** [comment] 2020-07-31 03:07
yes, Main graph's inputs and outputs must have type and shape information. Do you @skottmckay or @jcwchen want to create a PR to update the IR.md please?

**Comment by linkerzhang** [comment] 2020-07-31 03:08
It's not a BUG in checker but an issue of the documentation, btw. @matteosal

**Comment by jcwchen** [comment] 2020-07-31 04:47
> yes, Main graph's inputs and outputs must have type and shape information. Do you @skottmckay or @jcwchen want to create a PR to update the IR.md please?

Happy to help. Thank you for the explanation @skottmckay  @linkerzhang

**Comment by matteosal** [comment] 2020-07-31 09:34
> I believe graph inputs and outputs require a shape as well. Node inputs do not.

Well, for that matter, node inputs are not even required to exist at all. Then I think that this section I mentioned should also be made clearer:

> When the shape property is absent for an input, a tensor value of any shape may be passed from the caller. When the shape property is absent for an output, the caller should expect that the output value may be of any shape.

I think this should specify that: 
* The sentence applies to node I/O only
* Graph I/O must always specify a shape
* Node I/O can also be completely absent from the graph (and can be filled by shape inference)

**Comment by askhade** [comment] 2020-08-11 20:39
Closing this issue as the PR to address this is not merged.

**Closed by askhade** 2020-08-11 20:39 UTC
Labels: bug, ir
