### ISSUE TITLE
ONNX runtime produces different inference results for the same input

### ISSUE THREAD

**Issue by lihan** [onnx/onnx#3703] opened 2021-09-04 08:34 UTC
# Ask a Question

### Question

ONNX runtime produces different inference results for the same input

### Further information

Please refer the below notebook.
I used the same input to both PyTorch and ONNX model, but ONNX produces different results every time.

https://colab.research.google.com/drive/1cBd0MkQ804FXjWtOME1EB1-UiTXe1elp#scrollTo=bRLuTOjO2YQU

- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  transformers
**Model opset** (*e.g. 7*): 11

**Comment by jcwchen** [comment] 2021-09-04 15:57
Hi @lihan,
Initially I suspected the random is caused by `RandomUniformLike`, but I tried to set a fixed seed for it and the result is still random... Since this behavior happened during Runtime, please raise this question in ONNXRuntime to get the best help from the transformers experts there. Close it here now. Thank you!

**Closed by jcwchen** 2021-09-04 15:57 UTC
Labels: question
