### ISSUE TITLE
Shape inference for Unique assigns shape to empty string when optional outputs are provided.

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [onnx/onnx#3439] opened 2021-04-19 23:21 UTC
A value_info entry is added for empty string, which is not correct.

Onnx version 1.8.1.

https://www.dropbox.com/s/ljyo821c0b2miv5/test_unsorted_segment_sum.onnx?dl=1

**Comment by jcwchen** [comment] 2021-05-03 21:04
Hi @TomWildenhain-Microsoft,
Thank you for brining this up. It seems to me that it happens in all operators: onnx.shape_inference will still produce shape info even if the ouput is optional and an empty string... @gramalingam @askhade is it an expected behavior now? Or we need to go through every optional output from each operator and fix them. Thanks.

**Comment by gramalingam** [comment] 2021-05-03 21:16
It's a bug. It is sort of undocumented what InferenceContext::getOutputType should return for the case of missing optional outputs. One option is that it returns null. In this case, operator's shape-inference methods should check for this. This is the interpretation I have used conservatively when implementing inference-method. But we could have the context return a dummy TypeProto, but the trouble is we need to ensure all implementations (inlcuding ort's) does this.

**Comment by gramalingam** [comment] 2021-05-03 21:20
In other words, the handling can be left to ONNX side inference code (for all operators) or in the caller (implementing InferenceContext). Doing it in the caller is a bit less work.

**Comment by gramalingam** [comment] 2021-05-03 21:37
To clarify: we have several points here:
(a) The ONNX shape-inference (caller) code should ensure that it doesn't create entries for the empty-string. It should handle empty-string correctly. This is required because otherwise we would end up inference-error when we have multiple different optional outputs with different types mapped to same empty-string.
(b) I hope the ORT code for the above already does the correct thing in ORT.
(c) Finally, we should clean-up the point I made above about the contract between the caller and the operator-specific inference-code regarding optional inputs/outputs. But this could be done separately from (a), not necessarily same PR.

**Comment by askhade** [comment] 2021-05-03 22:15
I agree with (a) and (c)

ORT code already does the right thing. See here: https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/graph/graph.cc#L2103

In addition I think we should fix the inference mtds which are so obv wrong. In the particular case of Unique it seems to me the author missed the point that some outputs can be missing (as they are optional) This should be fixed... If there are other inference methods which have similar behavior we should fix them as well...

**Closed** 2021-11-22 22:40 UTC
Labels: bug, shape inference
