### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator ai.onnx.contrib::DCNv2

### ISSUE THREAD

**Issue by prabhuiitdhn** [onnx/onnx#3652] opened 2021-08-13 07:17 UTC
"DCNv2": I am implementing DEFT (Detection Embedding for Tracking) and It's architecture contains "DCNv2", It also have pytorch model and I am trying to convert to onnx and then to inference through onnx runtime. I am trying to add an operator to pytorch to convert to onnx model but I am unable to add operator to it.

### Can this operator be constructed using existing onnx operators?
"DCNv2" can't be constructed using existing onnx oprtators because It is a function and It is mandatory to add to onnx operator.

```
class DCNv2(Function):
    @staticmethod
    def symbolic(g, input, offset, mask, weight, bias, stride, padding, dilation, deformable_groups):
        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)
        #using this below line it is working
        # return g.op("DCNv2", input, offset, mask, weight, bias, stride_i=stride, padding_i=padding,
        #             dilation_i=dilation, deformable_groups_i=deformable_groups, )

        # But I am trying to add operator using custom domain which will help to inference but It is not working
        return g.op("ai.onnx.contrib::DCNv2", input, offset, mask, weight, bias, stride_i=stride, padding_i=padding,
                    dilation_i=dilation, deformable_groups_i=deformable_groups, )
```

### Are you willing to contribute it? (Y/N)
It depends, But now I am very close to my deadline and I wanted to execute it sucessfully.

Can you please take it as high priority? I have been stucked for last 15 days and raised many issue but still, I am unable to resolved it. I also tried to register custom operator after adding it nothing improves.

`register_custom_op_symbolic('::DCNv2', DCNv2, 9)`

It would be highly appreciable If I can resolve it asap. Thank you. Hope assignee/member will understand.

**Comment by jcwchen** [comment] 2021-08-13 17:32
Duplicate of https://github.com/onnx/onnx/issues/3648.  Let's track this issue there. Also, you can raise this issue in the converter (torch.onnx.export) because they might have more knowledge about it. Thanks!

**Closed by jcwchen** 2021-08-13 17:32 UTC
Labels: operator
