### ISSUE TITLE
how to print the weights & biases values of  model.onnx file using c++ 

### ISSUE THREAD

**Issue by abhishek27m1992github** [onnx/onnx#5945] opened 2024-02-18 12:10 UTC
# Ask a Question
how to print the weights & biases values of  model.onnx file using c++ ??
### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by gramalingam** [comment] 2024-02-19 01:29
Duplicate of issue #5946 .

**Closed by gramalingam** 2024-02-19 01:29 UTC
Labels: question
