### ISSUE TITLE
Installing package on Windows fails on too long filenames

### ISSUE THREAD

**Issue by Korijn** [onnx/onnx#2821] opened 2020-06-11 11:26 UTC
Installing onnx fails on my Windows 10 machine due to filepaths being too long ("De bestandsnaam of -extensie is te lang" is dutch for "The filename or -extension is too long"):

`ERROR: Could not install packages due to an EnvironmentError: [WinError 206] De bestandsnaam of -extensie is te lang: 'c:\\users\\korij_000\\appdata\\local\\pypoetry\\cache\\virtualenvs\\zb-hps-algo-bkp0o5gs-py3.6\\Lib\\site-packages\\onnx\\backend\\test\\data\\node\\test_negative_log_likelihood_loss_input_shape_is_NCd1d2d3_none_no_weight_negative_ignore_index_expanded\\test_data_set_0'`

I am able to work around this issue by installing to a folder higher up in my filesystem, but this filename looks a bit excessive.

**Comment by askhade** [comment] 2020-06-18 05:20
@jacky82226 : Let's fix this

**Comment by jacky82226** [comment] 2020-06-18 15:18
Hi @Korijn,
Thank you for reporting this bug! 
I was wondering that did you encounter other files also encounter this error?
I suspect the problem is [here](https://github.com/onnx/onnx/blob/cc2230603422bae893d5bc900d2d773ab34400a4/onnx/backend/test/case/node/negativeloglikelihoodloss.py#L428) and it has been update in a recent [PR](https://github.com/onnx/onnx/commit/f11f50fdb5f069eaf74af56f54edb0213559b833).
It surprisingly passed Windows-CI somehow, maybe it's because the maximum length of filename varies on different Windows machines.
I will propose a PR to fix this. Thanks.

**Comment by Korijn** [comment] 2020-06-18 16:28
If I may make a suggestion: don't include your tests and especially test data in your wheels. It's pointless and makes the package much bigger.

**Comment by jacky82226** [comment] 2020-06-19 17:12
> If I may make a suggestion: don't include your tests and especially your test data in your wheels. It's not needed at runtime and makes the package much bigger.

Good point. Did you use pip install onnx? It should be unnecessary to include them while installing the library...

**Comment by Korijn** [comment] 2020-06-19 17:34
> > If I may make a suggestion: don't include your tests and especially your test data in your wheels. It's not needed at runtime and makes the package much bigger.
> 
> Good point. Did you use pip install onnx? It should be unnecessary to include them while installing the library...

Yes I did.

**Comment by snnn** [comment] 2020-07-21 23:13
To get away from such issue:
1. When you install python, the install should have asked you if you want to apply a fix for this:https://stackoverflow.com/questions/51624449/python-setup-disabling-path-length-limit-pros-and-cons

2. If you're not using Windows 10, I suggest you upgrade it to. Starting with Windows 10 version 1607, if the filename is in Unicode, then you won't hit this limit.

3. Otherwise, use UNC path. "\\?\".

Make the test data file names shorter can  be a temporary solution, but it would be better if the underlying code could be fixed.

**Comment by Korijn** [comment] 2020-07-22 07:25
Thanks for the advice.

I read that you ended up not removing the test data because people are apparently using it? Just keep in mind that more and more people will start using the test data in the package and it will become harder and harder to remove it for you.

**Comment by prasanthpul** [comment] 2020-07-22 22:28
@Korijn please add your feedback about test data in the package in https://github.com/onnx/onnx/issues/2917

**Comment by askhade** [comment] 2020-08-12 05:32
Closing this issue as the long testnames have been changed. Rest of the discussion whether the test days should be part of onnx package itself will be tracked under issue #2917

**Closed** 2020-08-12 05:33 UTC
Labels: bug, build

**Comment by bigg-S** [comment] 2024-05-17 08:04
I recently had the same problem trying to install onnx in my Windows platform. I solved the issue by enabling long paths in the Windows registry editor and downloading cmake.
