### ISSUE TITLE
Pytorch export onnx：RuntimeError: Exporting the operator broadcast_tensors to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.

### ISSUE THREAD

**Issue by OneIsAll-w** [onnx/onnx#3339] opened 2021-03-17 03:07 UTC
# Bug Report

### Describe the bug

Exporting the operator broadcast_tensors to ONNX opset version 11 is not supported.But onnx still support the broadcast.

### System information
- Linux Ubuntu 18.04
- ONNX version ：1.8.1  
- Python version:3.7.6

### Reproduction instructions
- Describe the code to reproduce the behavior.
```
net.load_state_dict(torch.load('mse4096.pkl'))
net = net.eval()

input_shape = [1, 3, 256, 256]
input_data = torch.randn(input_shape)
export_onnx_file = "test.onnx"
torch.onnx.export(net, input_data, export_onnx_file, opset_version=11, do_constant_folding=True, input_names=["input"],
                  output_names=["output"], dynamic_axes={"input": {0: "batch_size"}, "output": {0: "batch_size"}})
...
```

**Comment by jcwchen** [comment] 2021-03-17 04:49
Hi @OneIsAll-w,
Duplicate of https://github.com/onnx/onnx/issues/3033. Similar to https://github.com/pytorch/pytorch/issues/30517.

As you mentioned, ONNX does support broadcast in some scenarios so I would say there might be some difficulties to do this in the converter (pytorch to ONNX). Please open an issue under the converter (torch.onnx.export is part of pytorch) to request this unsupported operator. In addition, you can check the supported operators for conversion here: https://pytorch.org/docs/stable/onnx.html#supported-operators. Close now and please reopen it if you have other ONNX related issues. Thank you!

**Closed by jcwchen** 2021-03-17 04:49 UTC
Labels: bug
