### ISSUE TITLE
Store large tensor values in separate files

### ISSUE THREAD

**Issue by postrational** [onnx/onnx#251] opened 2017-11-14 12:29 UTC
ONNX is designed to support the exchange of models which can grow quite large. We are already dealing with models which are hundreds of megabytes, soon they may be multiple gigabytes in size.

This can create problems when loading ONNX protobuf files in some memory-constrained environments.

To quote from the docs:

> Protocol Buffers are not designed to handle large messages. As a general rule of thumb, if you are dealing in messages larger than a megabyte each, it may be time to consider an alternate strategy.

https://developers.google.com/protocol-buffers/docs/techniques#large-data

We would like to suggest an optional method for storing tensor data in separate files, which can be loaded on demand.

One way to do this could be to add an optional `data_file` field to `TensorProto`. We could create an  `ExternalReference` message to store filenames or other external references (e.g. URL).
Please take a look at this PR https://github.com/onnx/onnx/pull/250

We would need to specify how to store the data in the external files (e.g using the tar format).

**Comment by postrational** [comment] 2017-11-15 10:02
Please let us know what you think about this idea. Should we pursue it further within ONNX?

**Comment by ezyang** [comment] 2017-11-15 11:22
I think this is definitely an issue that we will have to address at some point. Sub-gigabyte, the official protobuf implementations seem to perform acceptably (not great, but good enough), but it's definitely something we've noticed you have to be careful about. For example, we support two mechanisms for serializing tensors (protobuf repeated floats, or a raw string data) but for large data, only the raw string data mechanism is practical.

An alternative to putting tensor data in separate files is to standardize on a container format on top of protobuf which carries the proto, as well as the raw tensor data, e.g., RecordIO. We've wanted to avoid doing this because having models be a single proto is a very clear and easy to understand design, and an extra layer of indirection makes things more complex.

@postrational, are size problems already affecting you, or is this trying to stave off problems in the near future?

**Comment by postrational** [comment] 2017-11-15 16:08
@ezyang Yes, we already saw this issue in practice. 
A colleague got "out of memory" errors when loading VGG19 on a FP32 machine.

**Comment by rryan** [comment] 2017-11-20 18:03
TensorFlow's SavedModel format is designed to work around the limitations of protobuf. Any reason to not closely follow that format?

https://github.com/tensorflow/tensorflow/blob/eb84435170c694175e38bfa02751c3ef881c7a20/tensorflow/python/saved_model/README.md

**Comment by ezyang** [comment] 2017-11-27 22:22
OK, how about this:

* Let's support a multiple-file format for parameters. It will be the simplest possible thing: just `raw_data` blasted directly into a file, and a new field in `TensorProto` to reference the file in question.
* Let's write a converter in the onnx library for converting between this format and the existing `raw_data` format. Should be pretty simple.

Does anyone here want to contribute a patch? Any further bikeshedding?

**Comment by lutzroeder** [comment] 2017-11-29 10:45
Random thought: Would it make sense for TensorProto to reference (file, offset, length) to allow packing raw_data for multiple tensors into a single file if that's preferable?

**Comment by RanACohen** [comment] 2017-12-01 15:55
I would avoid putting direct reference from the ONNX to a particular file/offset.  
a better and more flexible approach is to 'id' the tensor in ONNX and let any other storing format simply provide means as it sees fit to return tensor given this 'id'.

Once could have freedom to implement packing of the tensors in multiple files, databases, URL's etc...

**Comment by lutzroeder** [comment] 2017-12-01 20:15
Downside of that approach would be that how to resolve those IDs might become specific to execution environment or the data files might have to get standardized as well?

**Comment by RanACohen** [comment] 2017-12-04 18:04
I would not put URL as the 'id'. 
a good 'id' is either a GUID, or the layer name + if it is weights or biases for example.
URL's should be built as a convention of the application on top of ONNX.

**Comment by lutzroeder** [comment] 2017-12-04 18:14
How would these resolve to real data? Imagine a tool loading an .onnx file. It hits a GUID and asks the user 'Please select the file that has the weights for this GUID' many times over? What would the standardized ID to file/data algorithm look like?

**Comment by gramalingam** [comment] 2017-12-04 18:55
May be issues like resolution of IDs are better left to the execution environment. 

One possibility is for the execution environment (or ONNX utilities) to provide an API that abstracts/approximates a container by providing the ability to parse a model from multiple files: a method takes a list of filenames (or whatever is desired) and returns an ONNX model, where the first file contains the model, and the remaining files are all TensorProto instances which are simply injected into the "initializer" list of the constructed model. (I guess we can work around the limitations, but if we want to standardize this representation, it is not clear how we can avoid discussing something like the container format that @ezyang mentioned).

**Comment by lutzroeder** [comment] 2017-12-04 20:35
Leaving it to the execution environment tends to not work out well for design-time and tools scenarios. .NET uses 'AssemblyName' IDs to resolve DLL dependencies and resolution rules work a certain way at runtime but are harder for an IDE to follow when there is no specific runtime environment to ask. Tools need to replicate that resolution logic in some way and for that it should be well defined. Starts with a converter that takes an .onnx file and writes the buffers to disk. How is that converter working if it's up to the runtime? A simple approach would be ID is a relative URL to a raw_data byte[] which is stored as just a byte[]. If there is a need to override the ID an environment can do so but loosing the benefits of generic tooling. There are other things to consider like having different sets of weights (model versions) for a single graph.

**Comment by gramalingam** [comment] 2017-12-06 21:48
What I meant was that a "complete file path" has disadvantages (lack of portability). A "relative file path" is better (but the interpretation of what this is relative to is determined by the execution environment anyway; relative to the ONNX model file makes sense, but the ONNX model location is external to the model itself). The final choice is a container format, formalized. Each seems to have its detractors.

Another way around the problem is to make all such externalized tensors additional "inputs" of the model, and just use the execution API provided to execute the model. Externalizing tensors anyway requires some support from the ONNX exporter of whatever framework the user uses (or a separate ONNX utility), so making such tensors as additional inputs can be done there. This doesn't require changes to ONNX itself.

**Comment by lutzroeder** [comment] 2017-12-07 00:51
Yes, relative path makes sense, full path less. The URL comment was more to illustrate that asking for more freedom while being well defined might be hard to standardize.

Having inputs vs. initializers marked separately is preferable as it makes the models more readable and understandable. Also being able to go from the model back to the constant data without involving the runtime environment is preferable for tooling and portability.

**Comment by ezyang** [comment] 2017-12-07 10:07
The constraint I want us to be sensitive to is this: there should be only one obvious way to do any given task. I understand the desire for more knobs, e.g., a way of serializing to one file, or multiple files, or a tarball, or to network (all of which might be the most appropriate in some context), but it makes things more confusing for users and implementors. (cough cough TensorFlow three saved model formats cough). Similarly, if we put in an extension point and let everyone do what they want, you lose the benefits of having a standard way of loading protobufs. It's OK to leave ourselves extension points (e.g., defining the tensor data identifier to be a URL seems like a good idea), but until there is a pressing need for fancy things, the standard should specify that there is only one valid form for the URI: a single filename, no scheme, no domain, no directories. There's also security concerns; models should not be allowed to declare that tensors should be loaded from arbitrary paths on a users system.

**Comment by lutzroeder** [comment] 2017-12-07 20:02
+1

**Comment by RanACohen** [comment] 2017-12-12 14:39
your need to have specific defines is understood and valued, but we should still keep the possibility to be open for proprietary implementations.  
So for sake of explicitness, I can provide several options:
1. a tar-ball file in which filenames are the 'id' file. tar filename base has the same name as the protobuf filename.
2. relative path to location of .pb file (less advised as this would make it hard to describe the whole thing with small set of files).

Thoughts?

**Comment by RanACohen** [comment] 2018-02-19 13:50
@ezyang Do you propose (for the sake of one-way-of-doing-things) to omit the raw_data included in PB and stick only to external storage?

**Comment by postrational** [comment] 2018-03-29 15:00
Hi everyone. I took notes on the discussion above and create a new PR which adds the functionality of storing tensor data in external files: https://github.com/onnx/onnx/pull/678

Please take a look and let us know what you think. Your comments are welcome.

**Comment by snnn** [comment] 2018-11-07 21:00
My two cents:

There are two things: message format and file format.  The first one is how you encode things, the second one is how you store things.  It's like H264/H265 vs AVI/MKV/MP4. It's always good to split them.    ModelProto, is the message format, like H264. There is no file format defined in ONNX spec. It's like, nobody said an ONNX model must be a binary file. You are free to choose what you want. I would think there is no need to extend ONNX IR. 

Back to binary world.  In the link @postrational posted at the beginning, I think it is quite clear:
1. if you are dealing in messages larger than a megabyte each, you are doing something wrong. Gigabytes? Totally wrong!
2. All you need is to handle a set of byte strings. It's, you can have a single giant file, which contains billions of byte strings, each of them, is part of the ModelProto. There is no limit of how large this file can be, but, for each of the byte strings, it should be less that 2MB.  

It also says: "Protocol Buffers do not include any built-in support for large data sets because different situations call for different solutions."  This statement is totally reasonable. Why do we think we have a general solution for all the situations? ONNX is a spec, not an implementation. It shouldn't regulate how people save their models. 

For file format, I would recommend [riegeli](https://github.com/google/riegeli/blob/master/doc/riegeli_records_file_format.md)

**Comment by linkerzhang** [comment] 2018-11-08 22:18
@postrational the solution you proposed is storing initializers' data externally per tensor, right? I have a simple thinking, why not separate the initializers into parts and store each part as external file (still using protobuf), something like,

message InitializerGroup{
  repeated TensorProto initializer=1;
}

message GraphProto {
  // The nodes in the graph, sorted topologically.
  repeated NodeProto node = 1;

  // The name of the graph.
  optional string name = 2;  // namespace Graph

  // A list of named tensor values, used to specify constant inputs of the graph.
  // Each TensorProto entry must have a distinct name (within the list) that
  // also appears in the input list.
  repeated TensorProto initializer = 5;

  // files that store part of initializer.
  // Each file is a serialization of InitializerGroup,
  // and must be in the same directory as the ModelProto serialization file
  **repeated string initializer_group_file_names=14;**
  
......
}

**Comment by EllieJinghan** [comment] 2018-11-13 18:42
Another solution is to store all the tensors binary data in one file and add a index to fetch binary for each tensor from the big binary data file. ExternalTensorEntriesProto is the proposed index pb format:
 // An entry of external tensor data
message ExternalTensorEntryProto {
  // id of the externl tensor data.
  // It is same as external_tensor_id in TensorProto
  string external_tensor_id = 1;

  // file name that stores the binary data. It must be in same directory as the ModelProto
  // For normal data, like int32, float,etc., the binary data is memory mapping of the tensor data.
  // For string, the binary data in the format like: str1_len str1_data str2_len str2_data ...
  // Note that multiple tensor data can be stored in the same binary file.
  string binary_file_name = 2;

  // offset and size of tensor data in the binary file
  int64 offset = 3;
  int64 size = 4;
}

message ExternalTensorEntriesProto {
  repeated TensorProtoEntry = 1;
}

**Comment by prasanthpul** [comment] 2019-03-26 15:21
I believe this is addressed by #678. Please re-open if needed

**Closed by prasanthpul** 2019-03-26 15:21 UTC
