### ISSUE TITLE
It doesn't save the outputs [Sorry this is a bug in ZhangGe6/onnx-modifier software]

### ISSUE THREAD

**Issue by pauldog** [onnx/onnx#4739] opened 2023-01-04 12:56 UTC
I click the download button and it saves the onnx. But when I reload it the outputs have disappeared.

**Comment by jcwchen** [comment] 2023-01-04 19:06
Hi @pauldog,
Could you please elaborate on this question? Which link are you referring to? (ONNX models from ONNX Model Zoo?) May I have your steps to reproduce this output disappeared issue?

**Comment by pauldog** [comment] 2023-01-05 08:52
Hi, yes. In particular I was trying to edit this file:
https://github.com/onnx/models/blob/main/vision/classification/mnist/model/mnist-1.onnx
Steps: Open it then click download. Then next time when I open the modified file it has no outputs.

Other files work though such as mnist-12.onnx

Thanks.

**Comment by jcwchen** [comment] 2023-01-05 15:58
Thank you for providing the steps. I can successfully download the [mnist-1.onnx](https://github.com/onnx/models/blob/main/vision/classification/mnist/model/mnist-1.onnx) and the downloaded model looks good.

> when I open the modified file it has no outputs.

How did you modify the model and how did you open the modified file? A clear reproduction steps would be very helpful. Thanks!

**Comment by pauldog** [comment] 2023-01-05 17:08
Hello, I didn't change anything. I just click the download button. I am using the Windows 64-bit version. 
Steps: open mnist-1.onnx file. Click download. Then open modified-mnist-1.onnx This is what I see:
[screenshot](https://drive.google.com/file/d/1INv51e-HG4tR-S4xeghCfSyinFMNFXKD/view?usp=share_link)
Thanks.

**Comment by jcwchen** [comment] 2023-01-06 15:55
No worries. Since it seems like an issue from another tool, I will close this one here. Feel free to reopen it if you still have other ONNX questions.

**Closed by jcwchen** 2023-01-06 15:55 UTC
Labels: bug
