### ISSUE TITLE
Concat nodes with null data

### ISSUE THREAD

**Issue by truncs** [onnx/onnx#3878] opened 2021-12-03 02:18 UTC
I have a subgraph that leads to null data in concat that ultimately results in failure on trt conversion. The checker run fine on the model.

The onnx files can be found over [here](https://drive.google.com/file/d/1bt7O9luctqJX00eBmWlBANve_C0p9Frg/view?usp=sharing). The code used to generate the graph is the following

```
import torch
import torch.nn as nn


class TestModule(nn.Module):
    def __init__(self):
        super(TestModule, self).__init__()

    def forward(self, ref):
        features = torch.zeros((1, 64, 100, 160))
        target = torch.zeros((1, 32, 100, 160))

        features[:,::2, :, :] = ref
        features[:, 1::2, :, :] = target 

        return features

 test = torch.randn(BATCH_SIZE, 32, 100, 160)
 torch.onnx.export(model, test, "/home/aditya/test.onnx", verbose=True, opset_version=11)

```
![netron](https://user-images.githubusercontent.com/157234/144533979-abc67726-f032-47e4-bb32-ac147d848d07.png)

### Question
Is this the expected behavior for this graph?

### Further information
trtexec error
```
[11/30/2021-17:04:14] [E] [TRT] parsers/onnx/ModelImporter.cpp:772: While parsing node number 5945 [Concat -> "2252"]:
[11/30/2021-17:04:14] [E] [TRT] parsers/onnx/ModelImporter.cpp:773: --- Begin node ---
[11/30/2021-17:04:14] [E] [TRT] parsers/onnx/ModelImporter.cpp:774: input: "2213"
input: "15020"
output: "2252"
name: "Concat_844"
op_type: "Concat"
attribute {
  name: "axis"
  i: 0
  type: INT
}

[11/30/2021-17:04:14] [E] [TRT] parsers/onnx/ModelImporter.cpp:775: --- End node ---
[11/30/2021-17:04:14] [E] [TRT] parsers/onnx/ModelImporter.cpp:778: ERROR: parsers/onnx/ModelImporter.cpp:179 In function parseGraph:
[6] Invalid Node - Concat_844
[graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 2: Internal Error (no further information)
```
- Is this issue related to a specific model?  
**Model name** (*e.g. mnist*):  N/A
**Model opset** (*e.g. 7*): 11

### Notes
Any additional information, code snippets.

**Comment by jcwchen** [comment] 2021-12-03 18:45
Hi @truncs,
Thank you for providing the details. I can repro this in ONNX that it passes onnx.checker. IIUC, concating with an empty tensor should be a valid case in ONNX. I can run this model without any error via ONNXRuntime and also `numpy.concatenate` allows concating with an empty array. Related issue: https://github.com/microsoft/onnxruntime/issues/681. I would say there might be other reason causing trt failure.

**Comment by jcwchen** [comment] 2021-12-15 00:03
It seems like you have found the root cause. Please track this issue in TensorRT. I will close this issue here. Thanks!

**Closed by jcwchen** 2021-12-15 00:03 UTC
Labels: question
