### ISSUE TITLE
How to remove warning from shape_inference

### ISSUE THREAD

**Issue by mengniwang95** [onnx/onnx#3696] opened 2021-09-02 06:00 UTC
# Ask a Question

### Question
![image](https://user-images.githubusercontent.com/65003808/131789984-b923d6eb-ef50-4332-a158-e3a3ff5062f2.png)
When I use python API shape_inference, there will be many warning infos, how can I remove these warnings?

**Comment by jcwchen** [comment] 2021-09-02 15:47
Hi @mengniwang95,
Since FusedConv is not an official ONNX op (it should a contrib_ops from ONNXRuntime), there is no schema definition for it in ONNX and shape_inference will throw this warning and stop shape inference anyway. This is an expected warning and you should probably just use onnxruntime.InferenceSession because onnx.shape_inference does not work with a model consists of unofficial ops. Thanks.

**Comment by askhade** [comment] 2021-09-05 22:13
@jcwchen: One of the problem is we are writing to std::cerr which is not desirable for all users. We should fix this... others have reported this too example: https://github.com/onnx/onnx/issues/2239

**Comment by fdwr** [comment] 2021-11-12 01:06
Yeah, writing directly to `std::cerr` is in appropriate for a low-level library, as it's the prerogative of the *calling* library (which actually does properly handle this in the case of ONNX Runtime) or of the application to emit user-visible messages.

**Comment by jcwchen** [comment] 2022-06-28 19:53
IIUC, after this PR: https://github.com/onnx/onnx/pull/3722 (which is included by ONNX 1.11) was merged, such a warning by std:cerr won't be thrown anymore. That is to say, if there is an unsupported operator, it will just stop shape inference and be silent. I will close this issue now. Thanks.

**Closed by jcwchen** 2022-06-28 19:53 UTC
Labels: question, enhancement
