### ISSUE TITLE
protobuf missing: Protobuf_INCLUDE_DIR error

### ISSUE THREAD

**Issue by cheers00** [onnx/onnx#1692] opened 2018-12-13 23:51 UTC
Hi, I am trying to install onnx from source but I am running into the following error.

I ran the following, without any problems

```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
```

but for the following command, 
`python setup.py install`

I get the following error.

```
CMake Error at /usr/local/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message)
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)

```

I did install protobuf-compiler using 
`sudo apt-get install protobuf-compiler libprotoc-dev
`
I then did export Protobuf_INCLUDE_DIR =/usr/local/include/google/protobuf/

But I still get the same error.

I have cmake of
```
cmake --version
cmake version 3.12.1

```

please let me know how to proceed. Thanks

**Comment by snnn** [comment] 2018-12-14 19:46
It's not a bug.

Please build and install protobuf by yourself. Make sure protoc is in your PATH. And, you'd better disable shared library while building protobuf.

**Comment by ginn24** [comment] 2019-10-31 01:44
ㅇdcompassionate_spence ㄴ

**Comment by askhade** [comment] 2019-11-13 02:51
#2452 fixes the failures and adds clear instructions for users

**Comment by askhade** [comment] 2019-11-15 21:43
Closing this issue as the above mentioned PR address this. Please reopen this or create a new one if this still exists for you

**Closed by askhade** 2019-11-15 21:43 UTC
Labels: build
