### ISSUE TITLE
I want the BN parameter could be changed with inputdata in inference, how to?

### ISSUE THREAD

**Issue by AmigoCDT** [onnx/onnx#3297] opened 2021-02-25 14:43 UTC
In Pytorch inference, we set `model.eval()` to set BN parameters as constant. But in GAN model, the `model.eval()` could not get good result, we hope the BN parameter could be influenced by input data, but not a constant.

So, I want to know how to get similar mode like 'model.eval()' in ONNX, i.e. do notthe BN parameters as constant?

Thanks.

**Comment by jcwchen** [comment] 2021-02-25 17:40
Duplicate of https://github.com/onnx/onnx/issues/3298. Close now

**Closed by jcwchen** 2021-02-25 17:40 UTC
Labels: question
