### ISSUE TITLE
Discrepancy between GroupNormalization paper and ONNX spec on scale and bias shape 

### ISSUE THREAD

**Issue by vsoorya** [onnx/onnx#5284] opened 2023-06-05 07:51 UTC
# Ask a Question

### Question
Why does the [ONNX specification](https://github.com/onnx/onnx/blob/main/docs/Operators.md#GroupNormalization) state that the scale and bias in GroupNormalization should be equivalent to the number of groups, while the GroupNorm paper suggests that they should have the shape of the number of channels?

### Further information
I see the `_group_normalization` function defined [here](https://github.com/onnx/onnx/blob/main/onnx/backend/test/case/node/groupnormalization.py) has a different implementation than what is suggested in the paper.
Paper - https://arxiv.org/pdf/1803.08494.pdf

**Comment by justinchuby** [comment] 2023-08-30 21:13
cc @gramalingam @xadupre

**Comment by gramalingam** [comment] 2023-08-30 23:24
I think this is the same question as https://github.com/onnx/onnx/issues/5466 ? If so, may be we can close this one. Hope the author of the op @yuanyao-nv can answer the question.

**Comment by justinchuby** [comment] 2023-08-30 23:28
Duplicate of https://github.com/onnx/onnx/issues/5466

**Closed by justinchuby** 2023-08-30 23:28 UTC
Labels: question, spec clarification
