### ISSUE TITLE
 onnx to CoreML

### ISSUE THREAD

**Issue by daylight0998** [onnx/onnx#2779] opened 2020-05-18 13:29 UTC
(1) I try to convert onnx model to mlmodel, but it's error:
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

(2) convert onnx model to mlmodel code is:
import os
import onnx
from onnx import onnx_pb
from onnx_coreml import convert

dataset_dir = "./"

model_in = os.path.join(dataset_dir, "vgnet.onnx")
model_out = os.path.join(dataset_dir, "vgnet.mlmodel")
model_file = open(model_in, 'rb')
model_proto = onnx_pb.ModelProto()
model_proto.ParseFromString(model_file.read())
print("prepare to convert...")
model = onnx.load_model('vgnet.onnx')
coreml_model = convert(model_proto,
minimum_ios_deployment_target='13')

(3) I debug it, it's interrupted at this file(./anaconda3/lib/python3.7/site-packages/onnx/shape_inference.py) : inferred_model_str = C.infer_shapes(model_str), the function is:

def infer_shapes(model): # type: (ModelProto) -> ModelProto
if not isinstance(model, ModelProto):
raise ValueError('Shape inference only accepts ModelProto, '
'incorrect type: {}'.format(type(model)))
model_str = model.SerializeToString()
inferred_model_str = C.infer_shapes(model_str)
return onnx.load_from_string(inferred_model_str)

(4) my onnx model had checked, it's fine, the code is:
import onnx
import torch

print(onnx.version)
device = torch.device('cpu' if torch.cuda.is_available() else 'cpu')
onnx_model = onnx.load("./vgnet.onnx")
onnx.checker.check_model(onnx_model)
print("checker check model")

the VGnet address: https://github.com/lelechen63/ATVGnet#model
What can be done to resolve this error

**Comment by daylight0998** [comment] 2020-05-20 01:43
@TMVector cloud you help me?

**Comment by TMVector** [comment] 2020-05-20 12:33
Hi @daylight0998, so it looks like it's the shape inference that is segfaulting. Can you confirm this by trying:
```python
import onnx
import onnx.shape_inference
model = onnx.load("./vgnet.onnx")
onnx.shape_inference.infer_shapes(model)
```

If so, it might be caused by a similar issue (/the same issue) as https://github.com/onnx/onnx/issues/2417. Can you try running this snippet to add graph inputs for all of the graph initializers:
```python
import onnx
import onnx.helper
import onnx.shape_inference

model = onnx.load("./vgnet.onnx")

# Add graph input for each initializer
existing_inputs = {v.name for v in model.graph.input}
model.graph.input.extend([
    onnx.helper.make_tensor_value_info(
        name = tensor.name,
        elem_type = tensor.data_type,
        shape = list(tensor.dims),
    )
    for tensor in model.graph.initializer
    if tensor.name not in existing_inputs
])

# Check if it passes shape inference now
onnx.shape_inference.infer_shapes(model)

# Save the resulting model
onnx.save(model, "model.patched.onnx")
```

**Comment by daylight0998** [comment] 2020-05-21 06:09
@TMVector thank you for your help!
I try to running 
onnx.shape_inference.infer_shapes(model)
 It is print:
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

So I am trying to add graph inputs for all of the graph initializers by your support,
it can save "model.patched.onnx" file. but when I  am trying to run convert :
coreml_model = convert(model_proto, preprocessing_args= {'image_scale': (1.0/255.0/0.5),
                                                         'blue_bias': (0.5 / 0.5),
                                                         'green_bias': (0.5 / 0.5),
                                                         'red_bias': (0.5 / 0.5),
                                                         'is_bgr': True},
                       image_input_names=['input'],
                       minimum_ios_deployment_target='13')
it had an new error:
Traceback (most recent call last):
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ff6b65a6a9ec>", line 1, in <module>
    runfile('/Users/vipkid/PycharmProjects/ai/ai-teacher/apps/landmark_to_image/onnx_to_mlModel.py', wdir='/Users/vipkid/PycharmProjects/ai/ai-teacher/apps/landmark_to_image')
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/vipkid/PycharmProjects/ai/ai-teacher/apps/landmark_to_image/onnx_to_mlModel.py", line 30, in <module>
    minimum_ios_deployment_target='13')
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/converter.py", line 627, in convert
    _convert_node_nd(builder, node, graph, err)
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 2389, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 526, in _convert_conv
    builder, node, graph, err)
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 71, in _add_conv_like_op
    return err.unsupported_op_configuration(builder, node, graph, "provided number axes {} not supported".format(rank))
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_error_utils.py", line 62, in unsupported_op_configuration
    self.rerun_suggestion)
TypeError: Error while converting op of type: Conv. Error message: provided number axes -1 not supported 
 Please try converting with higher minimum_ios_deployment_target.
You can also provide custom function/layer to convert the model.

I debug and checked my model, find it errored at this line:
ex_landmark1 = self.landmark_encoder_stage2(ex_landmark1)

My code:
    # input:
    # image = torch.ones(1, 3, 128, 128)
    # example_landmark = torch.ones(1, 86)
    # landmarks = torch.ones(1, 1, 86)

        image_feature1 = self.image_encoder1(image)
        image_feature = self.image_encoder2(image_feature1)
        ex_landmark1 = self.landmark_encoder(
            example_landmark.view(example_landmark.size(0), -1))
        ex_landmark1 = ex_landmark1.view(ex_landmark1.size(0), 1,
                                         image_feature.size(2),
                                         image_feature.size(3))
        ex_landmark1 = self.landmark_encoder_stage2(ex_landmark1)

function:
self.landmark_encoder_stage2 = nn.Sequential(conv2d(1, 256, 3, 1, 1),)

cloud you help me?

**Comment by TMVector** [comment] 2020-05-21 08:58
From a quick look at the converter source code[[0]], it looks like a rank of `-1` means it doesn't have the shape information it needs[[1]]. It looks like this is an open issue (https://github.com/onnx/onnx-coreml/issues/509) on the converter repo, so take a look at that :)

[0]: https://github.com/onnx/onnx-coreml/blob/master/onnx_coreml/_operators_nd.py#L71
[1]: https://github.com/apple/coremltools/blob/master/coremltools/models/neural_network/builder.py#L988-L989

**Comment by daylight0998** [comment] 2020-05-22 03:11
@TMVector thank you!
I solution this “Conv” problem with this:
I had a look at this issue  (onnx/onnx-coreml#509)  And add the following code at  onnx_coreml/_operators_nd.py (the same to this page： https://github.com/onnx/onnx-coreml/pull/524/files/11ef4be6cea8ea8f9d2042d53591f7d2438884bc#diff-137e66609eeaaa6436cb2a01692a3922R42-R52)

    if rank < 0 and node.op_type == "Conv" and "w_shape" in params_dict:
        rank = len(params_dict["w_shape"])


But, it has another "BatchNormalization" problem, the error code is:

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/vipkid/PycharmProjects/ai/ai-teacher/apps/landmark_to_image/onnx_to_mlModel.py", line 27, in <module>
    minimum_ios_deployment_target='13')
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/converter.py", line 627, in convert
    _convert_node_nd(builder, node, graph, err)
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 2395, in _convert_node_nd
    return converter_fn(builder, node, graph, err)
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_operators_nd.py", line 349, in _convert_bn
    err.unsupported_op_configuration(builder, node, graph, "provided number axes {} not supported".format(rank))
  File "/Users/vipkid/anaconda3/lib/python3.7/site-packages/onnx_coreml/_error_utils.py", line 62, in unsupported_op_configuration
    self.rerun_suggestion)
TypeError: Error while converting op of type: BatchNormalization. Error message: provided number axes -1 not supported 
 Please try converting with higher minimum_ios_deployment_target.
You can also provide custom function/layer to convert the model.

Can you help me again?

**Comment by daylight0998** [comment] 2020-05-28 03:06
@TMVector
Can you help me again?

**Comment by TMVector** [comment] 2020-05-29 21:20
Hi @daylight0998 sorry I forgot to reply. I don't really know details of the onnx-coreml converter; it's a shame you haven't received any help on your issue there.

It looks like it could be due to missing shape information again, so you could try the ONNX Runtime Nuphar [symbolic shape inference script](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/nuphar/scripts/symbolic_shape_infer.py) which is more powerful than the ONNX shape inference module (although still not all-powerful).

**Comment by askhade** [comment] 2021-06-04 15:51
@daylight0998 : Last year we fixed the graph level shape inference to allow initializers not be part of graph inputs... With this change the problem on onnx side should be resolved. the onnx=coreml issues still seem to be open and will have to be resolved from their side. 

I am closing this issue now... if you still encounter a problem which needs fix from onnx side please create a new issue. Thanks!

**Closed by askhade** 2021-06-04 15:51 UTC
Labels: converters
