### ISSUE TITLE
converting pytorch model having multiple input to onnx format and ending with runtime error.

### ISSUE THREAD

**Issue by tomshalini** [onnx/onnx#2679] opened 2020-03-24 19:50 UTC
Below is the code that i am trying to run and getting below mentioned error:

# Code
from torch.autograd import Variable
import torch
import numpy as np

########## Load the trained model from file ###########
model_path="/home/shalini/Downloads/stereo_rcnn_testing_1_6477.pth"
#model_path="/home/shalini/2D-FAN-300W.t7"

model = torch.load(model_path)
state_dict = model.state_dict(keep_vars=False)
########## Export the trained model to ONNX ##########
shape=[[3, 600, 1986], [3, 600, 1986], [3], [30, 5], [30, 5], [30, 5], [30, 5], [30, 6], [1]]

dummy_input = []
for i in range(len(shape)):
    input_shape = tuple([1] + shape[i])
    x = torch.randn(input_shape).cuda()
    dummy_input.append(x)

torch.onnx.export(model, tuple(dummy_input), "resnet.onnx")

# Error
Traceback (most recent call last):
  File "onnx.py", line 23, in <module>
    torch.onnx.export(model, tuple(dummy_input), "resnet.onnx")
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/onnx/utils.py", line 282, in _export
    example_outputs, propagate)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/onnx/utils.py", line 225, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/onnx/utils.py", line 192, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/jit/__init__.py", line 196, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace)(*args, **kwargs)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/nn/modules/module.py", line 492, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shalini/anaconda3/envs/env_stereo/lib/python3.6/site-packages/torch/jit/__init__.py", line 266, in forward
    out_vars, _ = _flatten(out)
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got int

**Comment by prasanthpul** [comment] 2020-04-17 21:56
dupe of #2711 ?

**Comment by TMVector** [comment] 2020-04-21 16:47
Hi @tomshalini, your model probably takes or returns an `int` from a `forward` function. You can read https://pytorch.org/docs/stable/onnx.html#tracing-vs-scripting and the answer on that page to `Does ONNX support implicit scalar datatype casting?`. I believe scripting can handle this kind of thing better and you could also try using `Tensor`s for all values.

I would recommend you first make sure you are using the latest version of PyTorch, and raise questions on the PyTorch discord https://discuss.pytorch.org/.

**Closed** 2020-09-04 00:43 UTC
