### ISSUE TITLE
Instantiate Neural Network class and run RunModel method

### ISSUE THREAD

**Issue by german-cantu** [onnx/onnx#5240] opened 2023-05-18 22:41 UTC
# Ask a Question

### Further information
- Relevant Area: 

- Is this issue related to a specific model?
**Model name**: 
**Model opset**:

**Comment by jcwchen** [comment] 2023-05-18 23:06
Duplicate of https://github.com/onnx/onnx/issues/5241. That one is more informative and therefore I will close this one.

**Closed by jcwchen** 2023-05-18 23:06 UTC
Labels: question
