### ISSUE TITLE
Resize op can not use input 'sizes' 

### ISSUE THREAD

**Issue by chuanqi305** [onnx/onnx#2559] opened 2020-01-20 06:01 UTC
According to the [documentation](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Resize) , The Resize op has 3-4 inputs, and we can use 'scales' or 'sizes' as it's scale parameters,  but when I set the scales to empty string to enable the 4th input 'sizes', the parser will failed by: 
Node (Resize__31)'s input 2 is marked single but has an empty string in the graph
So I think the scales should be 'optional' ?

**Comment by daquexian** [comment] 2020-01-28 09:01
Duplicate of https://github.com/onnx/onnx/issues/2451

The doc is somewhat wrong. Please refer to the [tests](https://github.com/onnx/onnx/blob/master/onnx/backend/test/case/node/resize.py#L298-L299) to pass an empty tensor for 'sizes' and 'roi' if they are not used.

**Comment by askhade** [comment] 2020-08-12 04:44
Closing this issue as it is being trcaked in #2451

**Closed by askhade** 2020-08-12 04:44 UTC
