### ISSUE TITLE
Error ONNX Export failed, Hardtanh not supported

### ISSUE THREAD

**Issue by BenjaminBout** [onnx/onnx#984] opened 2018-05-17 13:19 UTC
I tried to export a PyTorch model to ONNX and got this warning and error : 

`UserWarning: ONNX export failed on ATen operator hardtanh because torch.onnx.symbolic.hardtanh does not exist`
`RuntimeError: ONNX export failed: Couldn't export operator aten::hardtanh`

So after some researches, I understood that PyTorch can't export the operator Hardtanh. I tried to follow [the tutorial to add export support ](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md) but it seems like Hardtanh is not a standardized operator in ONNX. For this case, the tutorial says I have to add it to ONNX. How can I do that ? Is it possible to achieve this or should I wait for this operator to be supported or find another way to convert my model ?

**Comment by ghop02** [comment] 2018-05-21 18:47
Not sure what the policy is for duplicates, but this is a duplicate of #141

**Comment by houseroad** [comment] 2018-06-05 15:32
@ghop02 we will add HardTanh to ONNX by the end of June.

**Comment by prasanthpul** [comment] 2018-06-05 16:58
@ebarsoum hardtanh should be done as a function, right?

**Comment by Ac2zoom** [comment] 2018-06-22 18:17
https://github.com/onnx/onnx/pull/1136
We can discuss re-implementing as a function (rather than an activation function operator) down the line.

**Comment by sytelus** [comment] 2018-07-05 08:18
What is the status of this. It appears that without this operator popular SSD models cannot be exported to ONNX.

**Comment by Ac2zoom** [comment] 2018-07-05 16:41
https://github.com/pytorch/pytorch/pull/8804.  However, Hardtanh can also be equivalently expressed by Clip.

**Comment by sytelus** [comment] 2018-07-06 01:30
While I agree on equivalency, I think it would still be great to include this in ONNX supported ops because it's hard to change existing models.

**Comment by houseroad** [comment] 2018-07-14 06:07
Since the functionality is equivalent, as long as the exporter and importer know how to interpreter it, the model will work. So close the issue.

**Closed by houseroad** 2018-07-14 06:07 UTC
Labels: operator
