### ISSUE TITLE
SIGSEGV when convert_version

### ISSUE THREAD

**Issue by olegzhos** [onnx/onnx#4178] opened 2022-05-02 14:46 UTC
Hello everybody! When I try to convert a opset version of any onnx model to:
14-16 (when onnx==1.8 is installed), 
15-16 (when onnx==1.9 is installed), 
16 (when onnx==1.10 is installed)
with convert_version that I import from onnx.onnx_cpp2py_export.version_converter, I have the next error: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV). But I don't face this error if I convert to a target version less 14, 15 and 16 respectively. I was installing onnx with pip install onnx==... and I have installed ort with pip install onnxruntime==1.11.1 for all these cases.
Can you help me please or ask the information I should provide to resolve this error?

**Comment by jcwchen** [comment] 2022-05-02 14:53
Hi @olegzhos,
Could you please share the model which encountered this error to let me repro? Thanks.

**Comment by olegzhos** [comment] 2022-05-02 17:58
@jcwchen, for example:
[softmax.zip](https://github.com/onnx/onnx/files/8605148/softmax.zip)

**Comment by jcwchen** [comment] 2022-05-02 18:30
Thanks for providing the model. The latest ONNX (1.11.0) seems good for this model. Probably this issue has been fixed by https://github.com/onnx/onnx/pull/3893. Could you please try ONNX 1.11.0 and see whether the converted ONNX model is good?

**Comment by jcwchen** [comment] 2022-05-03 05:05
I just figured out the root cause: current version_converter crashes if the target version is higher than the latest opset_version because it prints a integer by %s. Opset 16 was introduced after ONNX 1.11 so that's why only ONNX 1.11 does not crash. To prevent crashes for older ONNX, simply using opset_version lower or equal the latest opset_version should help. (i.e., opset_version<=15 for ONNX 1.10; opset_version<=14 for ONNX 1.9; opset_version<=13 for ONNX 1.8). You can check the version_map here: https://github.com/onnx/onnx/blob/main/docs/Versioning.md. Going forward, https://github.com/onnx/onnx/pull/4182 this PR should resolve this kind of crash. Thanks for catching this bug.

**Comment by olegzhos** [comment] 2022-05-03 13:00
@jcwchen, you're welcome. Thank you for the reply!

**Closed** 2022-05-16 19:36 UTC
Labels: bug, version converter
