### ISSUE TITLE
## Error ONNX export failed: Couldn't export Python operator GridSampler ？？

### ISSUE THREAD

**Issue by heils003** [onnx/onnx#883] opened 2018-05-04 02:53 UTC
I tried to use ONNX to transform my Pytorch model but with error like this:
```
proto = trace.export(list(model.state_dict().values()), _onnx_opset_version)
RuntimeError: ONNX export failed: Couldn't export Python operator GridSampler
```
It seems ONNX can't find the same method like the Pytorch Function GridSampler. And it was setted `UNKNOWN_TYPE` on the Layer Operator???  How can I solve it ?

**Comment by houseroad** [comment] 2018-05-08 04:07
This means PyTorch does not know how to translate this op. Please check [the tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md) to fix the problem.

**Comment by IbnlaAhed** [comment] 2018-08-19 14:57
@heils003 i have the same error, have you find the solution?

**Comment by IbnlaAhed** [comment] 2018-08-19 15:03
@houseroad unfortunately Grid Sampler is not standardized in ONNX. Have you any proposition?
thx

**Comment by RunningLeon** [comment] 2020-10-27 09:18
@heils003 i have the same error, have you find the solution? thx

**Comment by OrkhanHI** [comment] 2020-12-28 08:21
any updates?

**Comment by tejal567** [comment] 2021-03-17 06:26
+1

**Comment by askhade** [comment] 2021-07-07 05:58
https://github.com/onnx/onnx/pull/3557 draft for grid sample

**Comment by askhade** [comment] 2021-07-07 05:59
duplicate of #2383. Closing this one.

**Closed by askhade** 2021-07-07 05:59 UTC
Labels: operator
