### ISSUE TITLE
Implement shape inference for Reshape from a Constant shape

### ISSUE THREAD

**Issue by anderspapitto** [onnx/onnx#981] opened 2018-05-16 16:42 UTC
in the fully general case, Reshape breaks the flow of shape inference, because the shape may be completely dynamic.

However, many cases are not fully general, and the shape input is the direct output of a Constant operator. In these cases we should be able to inspect the static argument input to the Constant operator, and infer the resulting shape of Reshape output accordingly.

In practice however, this is impossible due to the current shape inference API. There is no access to operators other than that currently being inferred.

This is especially unfortunate because a single Reshape early in the model can block the flow of type information through the entire model.

@linkerzhang @gramalingam @bddppq @dzhulgakov any thoughts on whether/how we might like to fix this? This is the type of thing that would have been trivial if we were building on top of the in-memory graph IR.

Three options I see are

- reintroduce the "shape" (static) argument to Reshape - so that rather than using a Constant node which is inaccessible, the information is available as a direct attribute of the Reshape operator.

- modify the shape inference API to allow other nodes to be visible in some way.

- Add a special case inference implementation for Reshape that bypasses the inference API entirely. It would not be contained in the OpSchema, but would be directly invoked by implementation.h when encountering a Reshape node.

**Comment by ebarsoum** [comment] 2018-05-16 17:09
Regarding the input from Constant OP, the input can be a constant from an expression and not just a single Const OP. Promoting attribute to an input will continue to happen depending on the flexibility needed, it would be good to have a generic solution, if we know the input is static at graph reconstruction time.

**Comment by anderspapitto** [comment] 2018-05-16 17:17
@ebarsoum sure, it's possible to expand the scope. However I'm particularly concerned about Reshape with what I'll call a "shape literal", since I know this occurs commonly.

**Comment by bddppq** [comment] 2018-05-23 05:53
Can we do a constant values folding pass first, and then extend the shape inference API to let shape inference functions access the values of initializers? The const folding pass will be useful for other purposes as well.

**Comment by linkerzhang** [comment] 2019-07-19 18:07
This was resolved by changing the inferencecontext api to expose (constant) input data for doing shape inference.

**Closed by linkerzhang** 2019-07-19 18:07 UTC

**Comment by vinicius-trev** [comment] 2020-09-10 20:46
Hi @linkerzhang, I'm currently facing some problems with constants in my model because it can't infer shapes for constants. Can you please explain a little bit more detailed the solution for doing shape inference with constants?

**Comment by gramalingam** [comment] 2020-09-10 21:26
Hi @vinicius-trev : can you provide more details about the example? What tensor did you expect a shape for but couldn't get? The shape-inference for the Constant op is here: https://github.com/onnx/onnx/blob/0af51551c81750f593022aa2a06c7ebf6bdfbe41/onnx/defs/generator/defs.cc#L69 ... if it is not producing the expected result for some example, it would be great to know more details.

**Comment by vinicius-trev** [comment] 2020-09-10 22:12
@gramalingam Yes, for sure, just complementing, I'm using ONNX library for python version 1.6.0. 
For the following model, the shape of the constant for the layer `Gather_2`, specifically Input 57 (as seen in the first picture), is empty. That empty shape breaks the rest of the inference.

`name: "57"
type {
  tensor_type {
    elem_type: 7
    shape {
    }
  }
}`

![image](https://user-images.githubusercontent.com/36710856/92814242-461be300-f399-11ea-826e-1e0e627cf729.png)

If you need the ONNX model, just inform an email that I can send it.
Thanks for your attention.

**Comment by gramalingam** [comment] 2020-09-10 23:39
An empty-shape is different from an unknown shape. A scalar, represented as a tensor with 0 dimensions, would have a shape that is an empty-shape. So, an empty-shape could be the correct expected result above. So, if some shape is not being inferred later, the reason could be something else. If there is nothing confidential in the model, may be you can attach it to the issue (zipped, if needed).

**Comment by vinicius-trev** [comment] 2020-09-11 00:14
Here it is
[model.zip](https://github.com/onnx/onnx/files/5205223/model.zip)

**Comment by gramalingam** [comment] 2020-09-11 22:07
Thanks. When I run the shape inference on the model it completes. The shapes of outputs of that node seem fine. Can you please clarify what you mean by "the empty shape breaks the rest of the inference"?

**Comment by vinicius-trev** [comment] 2020-09-11 22:43
Really? That's very strange. Here, after I run `shape_inference.infer_shapes()` and get the `model.graph.value_info`, those shapes seems to be empty, look at the attach [shapes.txt](https://github.com/onnx/onnx/files/5211741/shapes.txt). Can you show me the code where the output shape seems fine?

When I mean "the empty shape breaks the rest of the inference", is because the next layers after gather, whose are dependent on that output, can't be shape inferenced.

**Comment by gramalingam** [comment] 2020-09-11 23:58
As far as I can see, the shape inference at the next layer after gather works (the "Unsqueeze" nodes). However, subsequently, the two nodes where we are unable to produce an output shape is Slice_133 and Reshape_141. The case for Reshape_141 is understandable (this requires constant-propagation through the Gather=>Unsqueeze=>Concat=>Reshape path; so this will work if used in conjunction with an optimizer that can do this). But Slice_133 sounds a bit strange ... the output shape should be inferrable, I think, but is not inferred.

**Comment by vinicius-trev** [comment] 2020-09-14 19:40
Just another example, [this ONNX model](https://1drv.ms/u/s!Anc4TXKC1zvXoeQ6r4uvH4pMcygdOg?e=2jQP9J) suffers the same problem, since one not inferred shape invisibilized the inference of the others. I really don't know what is happening. The problem is that I've been using those shapes as key information. It would be great to understand why those shapes are empty, that way I can deal with those errors, keeping my code precise.
