### ISSUE TITLE
Why treat warnings as errors on windows even when ONNX_WERROR is off?

### ISSUE THREAD

**Issue by daquexian** [onnx/onnx#1936] opened 2019-04-15 08:05 UTC
https://github.com/onnx/onnx/blob/master/CMakeLists.txt#L404 and L451, L464

It is inconsistent between windows and linux/macos. On linux/macos the "treat warnings as errors" is controlled by ONNX_WERROR, but on windows it is always on.

**Comment by linkerzhang** [comment] 2019-04-19 06:57
it's more strict on windows by design.

**Comment by askhade** [comment] 2019-11-19 06:25
Closing this as by design. @daquexian  : If you have further questions on this topic please reopn this issue or create a new one

**Closed by askhade** 2019-11-19 06:25 UTC
Labels: build
