### ISSUE TITLE
Convert PyTorch (DeblurGANv2/FPNInception) to ONNX correctly

### ISSUE THREAD

**Issue by artvizi** [onnx/onnx#3208] opened 2021-01-12 07:54 UTC
### Question
How to convert PyTorch (DeblurGANv2/FPNInception) to ONNX correctly without mistakes?
How to find problem functions in the model?

I have converted the FPNInception model with dynamic axes to ONNX, but the inference result was wrong comparing to PyTorch.
When I did preparing model debug show me warnings with ConstantFill and ImageScaller op (Unknown).

In Pytorch, model loading is divided into main weights file and feature extraction load in the model class (InceptionResNetv2).
Also, I've tried to prepare TorchScript and load it into C++, but the inference result was wrong too.

### Related issue in PyTorch repo
https://github.com/pytorch/pytorch/issues/50685

### Project page
https://github.com/VITA-Group/DeblurGANv2

### Further information
**Model name**: DeblurGANv2 / FPNInception
**ONNX version**: 1.8.0 / 1.7.0
**ONNX opset**: 12
**PyTorch version**: 1.7.0 / 1.6.0

**Comment by jcwchen** [comment] 2021-01-12 16:23
Hi @artvizi,
The error might happen either in the converter (torch.onnx.export) or ONNXRuntime. 

First, I don't know whether `torch.onnx.export` supports DeblurGANv2/FPNInception right now, you can contact them about this and also get help for resolving the warnings during the conversion.

Once the ONNX model has been correctly converted and you still encounter the inference mismatch, then the problem would be in ONNXRuntime and you might need to go through each layer to inspect where the mismatch starts from and get help from the ONNXRuntime team to fix the issue. Thank you.

**Comment by chinhuang007** [comment] 2021-01-12 16:39
@artvizi ConstantFill and ImageScaller were experimental ops and deprecated since ONNX 1.4.1. The fact they are in your ONNX model indicates the issue is in Pytorch to ONNX conversion. I believe the default opset version for Pytorch converter is still very old. So please make sure the opset is set to 12 during the model export and see if it helps.

**Comment by artvizi** [comment] 2021-01-12 16:54
@chinhuang
ONNX opset: 12, directly in the export parameters
> @artvizi  007ConstantFill and ImageScaller were experimental ops and deprecated since ONNX 1.4.1. The fact they are in your ONNX model indicates the issue is in Pytorch to ONNX conversion. I believe the default opset version for Pytorch converter is still very old. So please make sure the opset is set to 12 during the model export and see if it helps.

**Comment by artvizi** [comment] 2021-01-12 16:56
@chinhuang007 I'm a novice and don't know how to inspect each layer particularly.

**Comment by chinhuang007** [comment] 2021-01-12 17:30
@artvizi You can use Netron, https://github.com/lutzroeder/netron, to inspect the converted ONNX model. If your ONNX model is in opset 12 and still has ConstantFill and ImageScaller ops, please open an issue in Pytorch converter repo.

**Comment by artvizi** [comment] 2021-01-18 10:28
@chinhuang007 I see "ConstantOfShape" nodes without any inputs.
Is it correct to see v12 and v6 input information about ONNX? (image below)
![Input](https://user-images.githubusercontent.com/52211516/104903372-ba970c00-59a1-11eb-989b-ffd61979ec50.jpg)

**Comment by artvizi** [comment] 2021-01-18 10:36
Maybe I should save that in Opset 13, but I have a message that Opset Version 13 is not supported in my actual event.

**Comment by jcwchen** [comment] 2021-06-14 02:51
I saw you have raised an issue in pytorch which is a better place to track this issue. Close here now. Thanks!

**Closed by jcwchen** 2021-06-14 02:51 UTC
Labels: question
