### ISSUE TITLE
RuntimeError: Exporting the operator bucketize to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

### ISSUE THREAD

**Issue by Tian14267** [onnx/onnx#3930] opened 2022-01-10 07:05 UTC
# Ask a Question

### Question
I going to change my **pytorch model** to **onnx**, But I get this error:
**RuntimeError: Exporting the operator bucketize to ONNX opset version 9 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.**

The detail is :
```
Traceback (most recent call last):
  File "torch2onnx.py", line 317, in <module>
    torch2onnx_speech()
  File "torch2onnx.py", line 217, in torch2onnx_speech
    output_names=['output'])
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/__init__.py", line 320, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/utils.py", line 111, in export
    custom_opsets=custom_opsets, use_external_data_format=use_external_data_format)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/utils.py", line 729, in _export
    dynamic_axes=dynamic_axes)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    module=module)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/utils.py", line 216, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/__init__.py", line 373, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/utils.py", line 1028, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/utils.py", line 982, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/root/anaconda3/envs/tts/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 125, in get_registered_op
    raise RuntimeError(msg)

```
### Further information
My pytorch model and code is here : [Fastspeech2](https://github.com/ming024/FastSpeech2)

**Comment by jcwchen** [comment] 2022-01-10 17:02
Hi @Tian14267,
Currently bucketize is still not supported by torch.onnx.export/ONNX/ONNXRuntime yet. I saw a possible workaround here: https://github.com/ming024/FastSpeech2/issues/98#issuecomment-952490935. Perhaps you can give it a try. Thanks!

Duplicate of https://github.com/microsoft/onnxruntime/issues/8297.

**Comment by Tian14267** [comment] 2022-01-11 03:45
Get it. Thank you very much.

**Closed** 2022-01-11 08:58 UTC
Labels: question, converters, enhancement
